server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://alicloud:3306/leyou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true
    username: yiyi
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
mybatis:
  type-aliases-package: cn.leyou.item.pojo